name: Publicar Libri Convites

on:
  push:
    branches:
      - main

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:

      - name: Baixar arquivos do GitHub
        uses: actions/checkout@v6

      - name: Publicar no Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

        run: |
          npx wrangler pages deploy . \
            --project-name=libri-convites \
            --branch=main